### ISSUE TITLE
Scrape "Seccion Electoral" field for members

### ISSUE THREAD

**Issue by chrismytton** [mysociety/argentina-diputados-buenos-aires#1]
We're currently scraping the "Distrito" field, but we also need the "Seccion Electoral" field for members.

<img width="662" alt="screen shot 2017-10-19 at 11 39 41" src="https://user-images.githubusercontent.com/22996/31767243-38f8d3fe-b4c2-11e7-9218-89f89991d1cb.png">

**Comment by jacksonj04** [comment]
Fixed in https://github.com/mysociety/argentina-diputados-buenos-aires/commit/979c4776d16c0d8453160ff31ad85b0f00659620, currently re-scraping on Morph.

**Comment by chrismytton** [comment]
@jacksonj04 Thanks!
